#!/usr/bin/env bash
# Scribing basic steps to install nginx web server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP' #nginx should be listed on port 80

# To access easily to webserver
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
