#!/usr/bin/env bash
# Writing script displaying Best School 10 times in 4 bad luck and in 8 good luck

number=1
while [ $number -le 10 ]
do
    if [ $number = 4 ]
    then
        echo "bad luck"
    elif [ $number = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((number+=1))
done
