#!/usr/bin/env bash
# Writing Bash script displaying time
# for 12 hours and 59 minutes

h=0
while [ $h -le 12 ];
do
	echo "Hour: $h"
	minuto=1
	while [ $minuto -le 59 ];
	do
		echo "$minuto"
		((minuto++))
	done
	((h++))
done
