#!/usr/bin/env bash
# Fixing web server to run Nginx as nginx user listening on port 8080.
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sed -i '/listen\s*80;/a\    listen 8080;' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
